generic: &generic
  modules:
    - notifier
    - router
    - view
  mail:
    to: 'w@zwartopwit.be'

development:
  <<: *generic

test:
  <<: *generic

production:
  <<: *generic
  mail:
    to: 'offerte@zwartopwit.be'
